---
title: "Insights on Storm and Bad Weather"
author: "Koushik Nagarajan"
date: "22 June 2015"
output: html_document
---

Synopsis here:.....

##Data Processing

```{r cache=TRUE}

data <- read.csv("data//repdata-data-StormData.csv.bz2")
data$EVTYPE <- tolower(data$EVTYPE)

```


##Data Analysis

```{r echo=FALSE}

summaryFatalities <- aggregate(data$FATALITIES ~ data$EVTYPE, data = data, FUN = sum)
colnames(summaryFatalities) <- c("EVTYPE", "FATALITIES")
 summaryFatalities <- summaryFatalities[order(summaryFatalities$EVTYPE), ]

summaryInjuries <- aggregate(data$INJURIES ~ data$EVTYPE, data = data, FUN = sum)
colnames(summaryInjuries) <- c("EVTYPE", "INJURIES")
summaryInjuries <- summaryInjuries[order(summaryInjuries$EVTYPE), ]

summaryHarmful <- cbind(summaryFatalities, summaryInjuries$INJURIES)
colnames(summaryHarmful) <- c("EVTYPE", "FATALITIES", "INJURIES")

summaryHarmful <- summaryHarmful[summaryHarmful$FATALITIES > 0, ]
summaryHarmful <- summaryHarmful[order(summaryHarmful$INJURIES, decreasing = TRUE), ]


summaryDamage <- aggregate(data$PROPDMG ~ data$EVTYPE, data = data, FUN = sum)
colnames(summaryDamage) <- c("EVTYPE", "DAMAGES")
```

#Most harmful with respect to population health
```{r}
library(ggplot2)
library(sqldf)
DF=sqldf("SELECT *,FATALITIES+INJURIES AS TotalEffect from summaryHarmful ORDER BY TotalEffect DESC LIMIT 10")
ggplot(data = DF, aes(x =EVTYPE, y = TotalEffect))+
        geom_bar(stat = "identity")+xlab("Event Type")+ylab("Number of Harmful Events")+
        labs(title="Top 10 Event Types With Highest Effect On Humans")

```


#Events have the greatest economic consequences
```{r}
top10Damage=sqldf("SELECT *  from summaryDamage ORDER BY DAMAGES DESC LIMIT 10")
ggplot(data = top10Damage, aes(x =EVTYPE, y = DAMAGES))+
        geom_bar(stat = "identity")+xlab("Event Type")+ylab("Damage Done")+
        labs(title="Top 10 Event Types With Highest Effect On Economy")
```
